name: Deployment

on:
    push:
      branches: [master, main]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4' 

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Run tests
        run: |
          go test ./... 

  deploy_to_render:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Render Deployment
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}

  push_to_gitlab:
    runs-on: ubuntu-latest
    needs: deploy_to_render 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Push to Gitlab
        env:
          TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
        run: |
          git fetch --unshallow "https://github.com/t1001001/prog2005-assignment-01.git"
          git config user.name "t1001001"
          git config user.email "tobias1001001@proton.me"
          git remote set-url origin "https://oauth2:$TOKEN@git.gvk.idi.ntnu.no/course/prog2005/prog2005-2025-workspace/tobi/prog2005-assignment-01.git"
          git push -u origin --all
          git push -u origin --tags
