name: Deployment

on:
    push:
      branches: [master, main]

jobs:
  deploy_to_render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Render Deployment
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}

  sync_to_gitlab:
    runs-on: ubuntu-latest
    needs: deploy_to_render  # Runs after the Render deployment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan git.gvk.idi.ntnu.no >> ~/.ssh/known_hosts

      - name: Mirror Push to GitLab
        run: |
          git remote add gitlab git@git.gvk.idi.ntnu.no:course/prog2005/prog2005-2025-workspace/tobi/prog2005-assignment-01.git
          git push --mirror gitlab